### ISSUE TITLE
Macro error serializing objects with numeric names

### ISSUE THREAD

**Issue by oleg-py** [suzaku-io/boopickle#101]
This code:

```scala
import boopickle.Default._
case object `1`
Pickle.intoBytes(`1`)
```

gives:

```
ScalaFiddle.scala:3: error: exception during macro expansion: 
scala.reflect.macros.ParseException: ';' expected but double literal found.
	at scala.reflect.macros.contexts.Parsers.$anonfun$parse$1(Parsers.scala:18)
	at scala.reflect.macros.contexts.Parsers.$anonfun$parse$1$adapted(Parsers.scala:17)
	at scala.collection.mutable.LinkedHashSet.foreach(LinkedHashSet.scala:93)
	at scala.reflect.macros.contexts.Parsers.parse(Parsers.scala:17)
	at scala.reflect.macros.contexts.Parsers.parse$(Parsers.scala:10)
	at scala.reflect.macros.contexts.Context.parse(Context.scala:6)
	at scala.reflect.macros.contexts.Context.parse(Context.scala:6)
	at boopickle.PicklerMaterializersImpl$.materializePickler(PicklerMaterializersImpl.scala:133)

  Pickle.intoBytes(`1`)
```

**Comment by ochrons** [comment]
Hm, yea, I suppose the macro doesn't surround the generated names with backticks or something. Damn you Scala for having all these complications 😆
