### ISSUE TITLE
Exception during macro expansion: 

### ISSUE THREAD

**Issue by rabzu** [suzaku-io/boopickle#66]
I would like to write a generic serializer, 

```
  def toBytes[T](event: T): Array[Byte] = {
    val bb = Pickle.intoBytes[T](event)
    val bytes = bb.array()
    //release buffer to pool
    BufferPool.release(bb)
    bytes
  }

  def fromBytes[T](bytes: Array[Byte]): T = {
    val bb = ByteBuffer.wrap(bytes)
    val event = Unpickle[T].fromBytes(bb)
    BufferPool.release(bb)
    event
  }
```

however

```
 I get exception during macro expansion: 
  at boopickle.PicklerMaterializersImpl$.materializePickler(PicklerMaterializersImpl.scala:71)
[error]     val bb = Pickle.intoBytes(event)

```

```
 exception during macro expansion: 
    at boopickle.PicklerMaterializersImpl$.materializePickler(PicklerMaterializersImpl.scala:71)
[error]     val event = Unpickle[T].fromBytes(bb)

```

**Comment by saucam** [comment]
Any updates on this ?

**Comment by ochrons** [comment]
A generic serializer is not possible to implement like this. The types need to be known at compile time for the macro driven pickler generation to work. You need to pass a suitable pickler implicitly to the methods,

```scala
def toBytes[T: Pickler](event: T): Array[Byte]
def fromBytes[T: Pickler](bytes: Array[Byte]): T
```
